### ISSUE TITLE
What firmware version are you running?

### ISSUE THREAD

**Issue by eccentricexit** [wabbitguy/Anycubic_Kobra_Max#4]
https://github.com/wabbitguy/Kobra_Max_PRUSA_Profiles/blob/9bdd731a5e9eabe53f7b7942a2a5b74d24ed91b3/README.md?plain=1#L24

What firmware version are you running?

--

First of all thank you for updating this, I'm willing to at least buy you some coffee for the update (if you want to setup a donate button).

I worked up the courage to try and use the Kobra Max to print a TPU wheel for a drone I'm working on. My first step was to come here and use your TPU profile as a starting point.

That note on the stock firware running the temperature higher answered so many questions and also made me wonder if I should or can update the firmware on my Kobra. I never touched it and Octoprint says:

`Your printer's firmware is a development build of Marlin (build date 20220720)`

I presume this is not the version you are running. Could you add your version to the readme?

Thanks again

**Comment by wabbitguy** [comment]
@eccentricexit thanks very much for the coffee offer, very much appreciated but not required. I do this just because I've already done it for so many years and just share to help out where I can.

In regards to the firmware, I'm using the 1.8.4 release version from my Github releases. And largely one of the reasons I do the firmware is because I need a printer to do specific things. One of those is filament changes, both layer based and within the same layer. The stock firmware simply doesn't allow either so I modify it. The thermistor correction was found after a few months of testing and we're still not 100% sure if it's the thermistor itself or the motherboard circuitry that's causing the wrong values from the stock one, but this fixes it.

I was also annoyed at the 0.05mm baby stepping, along with other items that Anycubic ignores because it might cause an uptick in tech support and therefore a profit loss.

Beyond that I found for the bed size of the Kobra Max, a 5 x 5 grid is a bit of a stretch so I changed it to 7 x 7. Of course more points would even be better but unfortunately the motherboard will run out of memory when that's attempted. So great it's 32 bit, but pathetic is the limited ram it has...

I changed the profiles readme to reflect the firmware version I am running. Thanks for the heads up on that.

If you want to update your firmware but don't want to start from scratch (i.e. all the bed levelling and so on), I could compile a custom version for you that would retain the 5 x 5 matrix levelling, but add in the missing features (well some of them any way because to gain them all also takes an LCD update). Just let me know if that would help out.
